version: "3.9"
services:
  client:
    ports:
      - "3000:3000"
  redis:
    image: "Sigmundgranaas/webrtc"
services:
  signal:
    ports:
      - "8000:8000"
  redis:
    image: "Sigmundgranaas/signal_server"