name: Build and deploy to production server

on:
  push:
    branches:
        - master 
        
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Login to Docker HUB
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_SECRET }}

    # Build the Docker image
    - name: Build
      run: |-
        docker build \
          --tag "sigmundgranaas/webrtc" \
          .
    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        docker push "${{ secrets.DOCKERHUB_USERNAME }}/webrtc" 
   
    - name: Reset the frontend pod
      uses: fifsky/ssh-action@master
      with:
        command: |
          kubectl delete pods --selector=app=webrtc
        host: ${{ secrets.DOMAIN }}
        user: ${{ secrets.NTNU_SERVER_USER }}
        key: ${{ secrets.NTNU_SERVER_PRIVATE_KEY }}
        args: "-tt"
